import Movies from '@/components/Movies';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-zinc-900">
        <Link href="/votes" className="absolute top-3 left-5 text-zinc-400">
          Votes
        </Link>
        <Movies />
      </main>
    </>
  );
}
